services:
  gamenest-app:
    build:
      context: ./gamenest
      dockerfile: Dockerfile
    container_name: gamenest-app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamenest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
      SPRING_BUILD_EXPORT_PATH: /app/final_builds/build
      SPRING_PRIVATE_KEY_PATH: /app/secrets/github-key.der
      SPRING_CORS_ORIGIN_URL: http://localhost:81
    volumes:
      - ./logs:/gamenest/logs
      # --- Mount the named game builds ---
      - game-builds:/app/final_builds
      # Make sure the source path on your host is correct
      - /Users/karizma/desktop/github-app/new-key.der:/app/secrets/github-key.der:ro # ro: read-only mounted volume
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: gamenest-postgres
    environment:
      POSTGRES_DB: gamenest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        API_URL: http://localhost:8085/api/v1
        GITHUB_APP_URL: https://github.com/apps/gamenestapplication
        GAME_BUILDS_URL: /builds
    container_name: gamenest-nginx
    ports:
      - "81:80"
    volumes:
      # --- Mount the game builds (read-only) ---
      - game-builds:/usr/share/nginx/html/builds:ro
    depends_on:
      gamenest-app:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
  game-builds:
